import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));const browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto(process.env.SITE_URL||'http://127.0.0.1:18765/jev_atlas.html');await page.waitForSelector('.model-card');await page.screenshot({path:'/tmp/jev-home.png',fullPage:false});
await page.locator('[data-filter="候选读出"]').click();if(await page.locator('.model-card').count()!==3)throw Error('filter');
await page.locator('#searchOpen').click();await page.locator('#searchInput').fill('LoRA');await page.waitForFunction(()=>document.querySelectorAll('.search-result').length>=5);if(await page.locator('.search-result').count()<5)throw Error('search');await page.locator('#closeSearch').click();
const diagrams=[];for(const id of ['decider','Kev','Laya','Kai','AnyJev','Eikos','Tev1','JevK5','foundation','comparison']){await page.evaluate(id=>location.hash='doc/'+id,id);await page.waitForFunction(id=>document.title.startsWith(id==='Kai'?'Decision 1.0 Kai':id==='foundation'?'基础课':id==='comparison'?'横向对照':id),id);await page.waitForSelector('#article h1');await page.waitForFunction(()=>[...document.querySelectorAll('#article .mermaid')].every(e=>e.querySelector('svg')));diagrams.push({id,svg:await page.locator('#article .mermaid svg').count(),math:await page.locator('#article .katex').count(),h2:await page.locator('#article h2').count()});}
await page.evaluate(()=>location.hash='doc/decider');await page.waitForTimeout(600);await page.screenshot({path:'/tmp/jev-reader.png',fullPage:false});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.screenshot({path:'/tmp/jev-mobile-reader.png',fullPage:false});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(overflow)errors.push('mobile overflow');await page.evaluate(()=>location.hash='home');await page.waitForTimeout(300);await page.screenshot({path:'/tmp/jev-mobile-home.png',fullPage:false});await page.locator('#menu').click();await page.locator('[data-nav="Kev"]').click();await page.waitForTimeout(500);if(await page.locator('.sidebar.open').count())errors.push('drawer not closed');
const data={errors,diagrams};fs.writeFileSync('/tmp/jev-browser-check.json',JSON.stringify(data,null,2));console.log(JSON.stringify(data,null,2));await browser.close();if(errors.length)process.exitCode=1;
